import React, { useState } from 'react';
import { Activity, ArrowRight, Clock3, FileText, LockKeyhole, Radio, ShieldCheck, Sparkles } from 'lucide-react';
import { AuditEntry, JITToken, Patient } from '../types/hdims';
import { calculateNEWS2 } from '../engine/news2Engine';
import { evaluateAccessScope } from '../engine/accessLattice';

interface Props {
  patient: Patient;
  history: { score: number; at: string }[];
  token: JITToken | null;
  recentLog?: AuditEntry;
  enteredAt?: string;
  testCount: number;
  onOpenClinic: () => void;
  onOpenPatient: () => void;
  onOpenAccess: () => void;
  onOpenAudit: () => void;
}

export const RiskMonitorPanel: React.FC<Props> = ({ patient, history, token, recentLog, enteredAt, testCount, onOpenClinic, onOpenPatient, onOpenAccess, onOpenAudit }) => {
  const [showAssist, setShowAssist] = useState(false);
  const score = calculateNEWS2(patient.vitals);
  const previous = history.length > 1 ? history[history.length - 2].score : null;
  const direction = previous === null ? 'Trend needs another reading' : score.total > previous ? `Rising from ${previous}` : score.total < previous ? `Falling from ${previous}` : `Unchanged from ${previous}`;
  const specialist = evaluateAccessScope('ON_CALL_CARDIOLOGIST', score.tier, token, patient.id);
  const response = evaluateAccessScope('RAPID_RESPONSE_LEAD', score.tier, token, patient.id);
  const contributors = [
    { label: 'Breathing rate', value: `${patient.vitals.respirationRate}/min`, points: score.subscores.respirationRate },
    { label: 'Oxygen saturation', value: `${patient.vitals.spo2}%`, points: score.subscores.spo2 },
    { label: 'Supplemental oxygen', value: patient.vitals.oxygenSupplement ? 'Yes' : 'No', points: score.subscores.oxygenSupplement },
    { label: 'Systolic pressure', value: `${patient.vitals.systolicBp} mmHg`, points: score.subscores.systolicBp },
    { label: 'Pulse', value: `${patient.vitals.pulseRate} bpm`, points: score.subscores.pulseRate },
    { label: 'Consciousness', value: patient.vitals.consciousness.toLowerCase(), points: score.subscores.consciousness },
    { label: 'Temperature', value: `${patient.vitals.temperature}°C`, points: score.subscores.temperature },
  ].filter(item => item.points > 0).sort((a, b) => b.points - a.points).slice(0, 3);
  const marker = score.tier === 'CRITICAL' ? 'bg-rose-100 text-rose-800' : score.tier === 'MEDIUM' ? 'bg-amber-100 text-amber-900' : 'bg-[#e8f1e2] text-[#315b39]';

  return <section className="mb-5 overflow-hidden rounded-[26px] border border-[#dce6d7] bg-white shadow-sm" aria-label="Patient risk monitor">
    <div className="flex flex-wrap items-start justify-between gap-4 border-b border-[#e9eee6] px-5 py-5 md:px-7">
      <div><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.16em] text-[#63805d]"><Radio size={15} /> Risk monitor</div><h3 className="mt-2 text-2xl font-extrabold tracking-tight text-[#17281c]">{patient.name} <span className="text-sm font-medium text-slate-500">· {patient.id}</span></h3><p className="mt-1 text-sm text-slate-500">Current clinical state and the next response for this patient</p></div>
      <div className="flex flex-wrap gap-2"><button onClick={() => setShowAssist(value => !value)} aria-expanded={showAssist} className="inline-flex items-center gap-1.5 rounded-full px-3 py-2.5 text-sm font-bold text-[#456747] hover:bg-[#f1f6ed]"><Sparkles size={15} /> AI assist</button><button onClick={onOpenPatient} className="rounded-full border border-[#cddcc7] bg-white px-4 py-2.5 text-sm font-bold text-[#315b39] hover:bg-[#f5f9f2]">Open chart</button><button onClick={onOpenClinic} className="inline-flex items-center gap-2 rounded-full bg-[#24472b] px-4 py-2.5 text-sm font-bold text-white transition hover:bg-[#38643e] focus-visible:outline focus-visible:outline-4 focus-visible:outline-[#a5c592]">Enter new vitals <ArrowRight size={16} /></button></div>
    </div>
    {showAssist && <div className="border-b border-[#e9eee6] bg-[#f8faf6] px-5 py-4 md:px-7"><div className="flex items-center gap-2 text-sm font-bold text-[#29442e]"><Sparkles size={16} /> Review draft</div><p className="mt-2 text-sm leading-relaxed text-slate-700">{patient.name} has a current NEWS2 of {score.total} ({score.tier.toLowerCase()}). {direction}. {contributors.length ? `The main score contributors are ${contributors.map(item => `${item.label.toLowerCase()} ${item.value}`).join(', ')}.` : 'No vital sign adds points to the score.'} {testCount + patient.labReports.length ? 'Earlier reports are available for clinician comparison.' : 'No earlier test report is listed.'}</p><p className="mt-2 text-xs text-slate-500">This draft is generated by transparent rules from the displayed data. A clinical AI model is not connected; a clinician must check the source readings.</p></div>}
    <div className="grid gap-5 p-5 md:p-7 lg:grid-cols-[.85fr_1fr_1fr]">
      <div className="rounded-[22px] bg-[#f5f7f3] p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#5d765b]"><Activity size={17} /> Current NEWS2</div><div className="mt-4 flex items-end gap-3"><strong className="text-6xl font-extrabold leading-none text-[#17281c]">{score.total}</strong><span className={`mb-1 rounded-full px-3 py-1.5 text-xs font-extrabold ${marker}`}>{score.tier === 'LOW' ? 'Stable' : score.tier === 'MEDIUM' ? 'Review soon' : 'Urgent review'}</span></div><p className="mt-4 text-sm font-semibold text-[#29442e]">{direction}</p><p className="mt-1 text-xs text-slate-500">{history.length > 1 ? `Latest entry ${history[history.length - 1].at}` : 'One current reading available'}</p><div className="mt-4 border-t border-[#dfe8da] pt-3 text-xs"><strong className="text-[#29442e]">What drives this score</strong><p className="mt-1 leading-relaxed text-slate-600">{contributors.length ? contributors.map(item => `${item.label} ${item.value} (+${item.points})`).join(' · ') : 'No NEWS2 points from the current vitals.'}</p></div></div>
      <div className="rounded-[22px] border border-[#e5ebe1] p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#5d765b]"><FileText size={17} /> Signals available</div><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-2"><span>Vitals</span><strong>{enteredAt ? 'Clinic entry' : 'Supplied sample'}</strong></div><div className="flex justify-between gap-2"><span>Digital record</span><strong>{patient.abdmStatus === 'SYNCED' ? 'Sample linked' : patient.abdmStatus === 'PARTIAL_CACHE' ? 'Partial sample' : 'Offline sample'}</strong></div><div className="flex justify-between gap-2"><span>Test reports</span><strong>{testCount + patient.labReports.length} available</strong></div><div className="flex justify-between gap-2"><span>Live device feed</span><strong>Not connected</strong></div></div><p className="mt-4 text-xs leading-relaxed text-slate-500">Missing or old signals need clinical review. The demo score uses the vitals shown; reports are context only.</p></div>
      <div className="rounded-[22px] border border-[#e5ebe1] p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-[#5d765b]"><LockKeyhole size={17} /> Response and access</div><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-2"><span>Assigned nurse</span><strong>Vitals and medicines</strong></div><div className="flex justify-between gap-2"><span>On-call specialist</span><strong>{specialist.historicalEHR ? 'Time-limited detail' : specialist.liveVitals ? 'Clinical summary' : 'No active scope'}</strong></div><div className="flex justify-between gap-2"><span>Rapid response</span><strong>{response.liveVitals ? 'Critical scope' : 'Standby'}</strong></div><div className="flex justify-between gap-2"><span>Referral hospital</span><strong>Handoff required</strong></div><div className="flex justify-between gap-2"><span>Family contact</span><strong>Not shared</strong></div><div className="flex items-center gap-1 text-xs text-slate-500"><Clock3 size={13} /> {token?.patientId === patient.id && token.expiresAt > Date.now() ? `Specialist grant ends ${new Date(token.expiresAt).toLocaleTimeString()}` : 'No active specialist grant'}</div></div><div className="mt-4 flex flex-wrap gap-3"><button onClick={onOpenAccess} className="text-xs font-bold text-[#38643e] underline underline-offset-4">View access</button><button onClick={onOpenAudit} className="text-xs font-bold text-[#38643e] underline underline-offset-4">Read audit</button></div></div>
    </div>
    <div className="flex flex-wrap items-start gap-2 border-t border-[#e9eee6] bg-[#fbfcfa] px-5 py-4 text-xs text-slate-600 md:px-7"><ShieldCheck size={16} className="shrink-0 text-[#63805d]" /><span><strong className="text-[#29442e]">Latest recorded change:</strong> {recentLog?.plainLanguage || 'No new access or risk change recorded for this patient in this session.'}</span></div>
    <p className="px-5 pb-4 text-xs text-slate-500 md:px-7">This is an early warning monitor using current NEWS2 and entered readings. It does not yet predict future deterioration or ingest a live hospital feed.</p>
  </section>;
};
