import React, { useEffect, useState } from 'react';
import { Activity, ArrowRight, ClipboardList, FileText, HeartPulse, Hospital, Pill, Printer, Stethoscope, Type, UserRoundCheck } from 'lucide-react';
import { Patient, Vitals } from '../../types/hdims';
import { calculateNEWS2 } from '../../engine/news2Engine';
import { MedicineEntry, TestEntry } from './CareTimelineView';

interface Props {
  patients: Patient[];
  selectedPatientId: string;
  onPatientChange: (id: string) => void;
  onSaveVitals: (vitals: Vitals, enteredBy: string) => void;
  lastEnteredAt?: string;
  tests: TestEntry[];
  medicines: MedicineEntry[];
  onOpenRecords: () => void;
  onOpenPatient: () => void;
  onOpenRiskView: () => void;
}

const tierLabel = { LOW: 'Stable', MEDIUM: 'Review soon', CRITICAL: 'Urgent review' };
const tierClasses = { LOW: 'bg-[#e6f0e0] text-[#345b36]', MEDIUM: 'bg-amber-100 text-amber-900', CRITICAL: 'bg-rose-100 text-rose-800' };

export const ClinicVisitView: React.FC<Props> = ({ patients, selectedPatientId, onPatientChange, onSaveVitals, lastEnteredAt, tests, medicines, onOpenRecords, onOpenPatient, onOpenRiskView }) => {
  const patient = patients.find(item => item.id === selectedPatientId) || patients[0];
  const [largeText, setLargeText] = useState(false);
  const [editingVitals, setEditingVitals] = useState(false);
  const [enteredBy, setEnteredBy] = useState('Clinic staff');
  const [draft, setDraft] = useState<Vitals>(patient.vitals);
  useEffect(() => { setDraft(patient.vitals); setEditingVitals(false); }, [patient.id, patient.vitals]);
  const score = calculateNEWS2(patient.vitals);
  const latestTest = tests.filter(item => item.patientId === patient.id).sort((a, b) => b.collectedOn.localeCompare(a.collectedOn))[0];
  const sampleTest = patient.labReports[0];
  const activeMeds = medicines.filter(item => item.patientId === patient.id && (!item.endsOn || item.endsOn >= new Date().toLocaleDateString('en-CA')));
  const sampleMeds = patient.prescriptions.filter(item => item.status === 'ACTIVE');
  const setNumber = (field: keyof Vitals, value: number) => setDraft(previous => ({ ...previous, [field]: value }));

  return <div className={`clinic-page mx-auto max-w-6xl px-5 py-7 md:px-8 md:py-9 ${largeText ? 'clinic-large' : ''}`}>
    <div className="clinic-hero mb-5 overflow-hidden rounded-[28px] px-6 py-7 text-white md:px-9 md:py-9">
      <div className="relative z-10 flex flex-wrap items-start justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#c7dbb7]">HDIMS · Community clinic</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold leading-tight tracking-tight md:text-5xl">Good care starts close to home.</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-white/80">Check existing records, enter today’s observations, and decide what care is needed next. A staff member can guide the visit; the patient does not need a phone.</p></div><button type="button" onClick={() => setLargeText(value => !value)} aria-pressed={largeText} className="clinic-hero-button no-print flex items-center gap-2 rounded-full bg-white px-4 py-2.5 text-sm font-bold text-[#24472b]"><Type size={17} /> {largeText ? 'Standard text' : 'Larger text'}</button></div>
      <div className="relative z-10 mt-8 grid gap-3 sm:grid-cols-3"><div className="clinic-step"><span>01</span><strong>Find the person</strong><small>Staff selects a record</small></div><div className="clinic-step"><span>02</span><strong>Check before repeating</strong><small>See the last result and medicines</small></div><div className="clinic-step"><span>03</span><strong>Assess and hand off</strong><small>Enter vitals or refer for review</small></div></div>
    </div>

    <div className="grid gap-5 lg:grid-cols-[minmax(0,1.35fr)_minmax(300px,.8fr)]">
      <div className="space-y-5">
        <section className="clinic-card"><div className="flex flex-wrap items-end justify-between gap-3"><div><span className="clinic-eyebrow">1 · Start the visit</span><h3 className="clinic-title">Who is here today?</h3></div><span className="rounded-full bg-[#f0f3ed] px-3 py-1.5 text-xs font-semibold text-[#456747]">Staff-assisted check-in</span></div><label htmlFor="clinic-patient" className="mt-5 block text-sm font-bold text-[#283b2c]">Patient</label><select id="clinic-patient" value={patient.id} onChange={event => onPatientChange(event.target.value)} className="clinic-select mt-2 w-full rounded-2xl border border-[#d2decc] bg-white px-4 py-3 font-bold text-[#17281c]">{patients.map(item => <option key={item.id} value={item.id}>{item.name} · {item.id}</option>)}</select><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="clinic-info"><span>Age</span><strong>{patient.age} years</strong></div><div className="clinic-info"><span>Clinic record</span><strong>{patient.id}</strong></div></div><p className="mt-4 text-sm text-slate-500">A clinician can review and correct the person’s history before using it for care.</p></section>

        <section className="clinic-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="clinic-eyebrow">2 · Check what is known</span><h3 className="clinic-title">Records from earlier care</h3></div><button type="button" onClick={onOpenRecords} className="clinic-link no-print">Open care records <ArrowRight size={17} /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="clinic-record"><span className="clinic-record-icon"><FileText size={20} /></span><strong>Most recent test</strong>{latestTest ? <><span>{latestTest.name}</span><small>{latestTest.facility} · {latestTest.collectedOn}</small><small>{latestTest.reviewOn ? `Review set for ${latestTest.reviewOn}` : 'No repeat date recorded'}</small></> : sampleTest ? <><span>{sampleTest.testName}</span><small>Supplied sample record · {sampleTest.collectedAt}</small><small>No repeat date recorded</small></> : <span>No test on file</span>}</div><div className="clinic-record"><span className="clinic-record-icon"><Pill size={20} /></span><strong>Listed medicines</strong><span>{activeMeds.length + sampleMeds.length} current entries</span><small>{activeMeds[0]?.name || sampleMeds[0]?.medicineName || 'No medicine listed'}</small><small>Confirm dose and side effects at every visit</small></div></div><p className="mt-4 text-sm text-slate-500">Previous records help the clinician decide what needs repeating. A date alone cannot make that decision.</p></section>

        <section className="clinic-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="clinic-eyebrow">3 · Assess today</span><h3 className="clinic-title">Today’s vital signs</h3></div><button type="button" onClick={() => setEditingVitals(value => !value)} className="clinic-action no-print"><Activity size={17} /> {editingVitals ? 'Close form' : 'Enter vitals'}</button></div><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="clinic-vital"><span>SpO₂</span><strong>{patient.vitals.spo2}%</strong></div><div className="clinic-vital"><span>Pulse</span><strong>{patient.vitals.pulseRate}</strong><small>bpm</small></div><div className="clinic-vital"><span>Breathing</span><strong>{patient.vitals.respirationRate}</strong><small>/min</small></div><div className="clinic-vital"><span>Blood pressure</span><strong>{patient.vitals.systolicBp}</strong><small>systolic</small></div></div><p className="mt-3 text-xs text-slate-500">{lastEnteredAt ? `Staff entry: ${lastEnteredAt}` : 'Showing supplied demo vitals. No new clinic entry this session.'}</p>
          {editingVitals && <form onSubmit={event => { event.preventDefault(); onSaveVitals(draft, enteredBy.trim() || 'Clinic staff'); setEditingVitals(false); }} className="clinic-vitals-form no-print mt-5 grid gap-3 rounded-2xl bg-[#f5f8f3] p-4 sm:grid-cols-2"><label>Oxygen saturation (%)<input required type="number" min="0" max="100" value={draft.spo2} onChange={e => setNumber('spo2', Number(e.target.value))} /></label><label>Pulse (beats/min)<input required type="number" min="0" max="250" value={draft.pulseRate} onChange={e => setNumber('pulseRate', Number(e.target.value))} /></label><label>Breathing rate (/min)<input required type="number" min="0" max="80" value={draft.respirationRate} onChange={e => setNumber('respirationRate', Number(e.target.value))} /></label><label>Systolic pressure (mmHg)<input required type="number" min="0" max="300" value={draft.systolicBp} onChange={e => setNumber('systolicBp', Number(e.target.value))} /></label><label>Temperature (°C)<input required type="number" step="0.1" min="25" max="45" value={draft.temperature} onChange={e => setNumber('temperature', Number(e.target.value))} /></label><label>Consciousness<select value={draft.consciousness} onChange={e => setDraft(previous => ({ ...previous, consciousness: e.target.value as Vitals['consciousness'] }))}><option value="ALERT">Alert</option><option value="VOICE">Responds to voice</option><option value="PAIN">Responds to pain</option><option value="UNRESPONSIVE">Unresponsive</option></select></label><label className="flex-row items-center gap-3 sm:col-span-2"><input type="checkbox" checked={draft.oxygenSupplement} onChange={e => setDraft(previous => ({ ...previous, oxygenSupplement: e.target.checked }))} /> Supplemental oxygen</label><label className="sm:col-span-2">Entered by<input required value={enteredBy} onChange={e => setEnteredBy(e.target.value)} /></label><button type="submit" className="clinic-action sm:col-span-2"><HeartPulse size={17} /> Save this session’s vitals</button></form>}
        </section>
      </div>

      <div className="space-y-5"><section className="clinic-card"><span className="clinic-eyebrow">Risk and next step</span><h3 className="clinic-title">Clinical review</h3><div className="mt-5 flex items-center gap-4"><span className={`grid h-20 w-20 shrink-0 place-items-center rounded-[24px] text-3xl font-extrabold ${tierClasses[score.tier]}`}>{score.total}</span><div><span className={`inline-block rounded-full px-3 py-1 text-xs font-extrabold ${tierClasses[score.tier]}`}>{tierLabel[score.tier]}</span><p className="mt-2 text-sm text-slate-500">NEWS2 from the vitals shown here</p></div></div><p className="mt-5 text-sm leading-relaxed text-slate-600">{score.tier === 'CRITICAL' ? 'The demo score indicates urgent clinical assessment and a possible higher-level referral.' : score.tier === 'MEDIUM' ? 'The demo score indicates prompt clinical review.' : 'The demo score is in the lower risk tier. Continue clinical assessment.'}</p><div className="mt-5 flex flex-col gap-2"><button type="button" onClick={onOpenPatient} className="clinic-action no-print w-full"><Stethoscope size={17} /> Open patient chart <ArrowRight size={17} /></button><button type="button" onClick={onOpenRiskView} className="clinic-outline no-print w-full"><Hospital size={17} /> Risk and escalation view</button></div><p className="mt-4 text-xs text-slate-500">A clinician must interpret this score alongside symptoms and examination. No referral is sent automatically.</p></section>
        <section className="clinic-card clinic-family"><span className="clinic-eyebrow">For the patient or caregiver</span><h3 className="clinic-title">A simple handoff</h3><div className="mt-4 space-y-3 text-sm leading-relaxed"><p><UserRoundCheck className="mr-2 inline h-5 w-5 text-[#54765a]" /> Your clinic can look at earlier test reports and medicines with you.</p><p><ClipboardList className="mr-2 inline h-5 w-5 text-[#54765a]" /> Ask when the next review is planned and whether a new test is needed.</p><p><Printer className="mr-2 inline h-5 w-5 text-[#54765a]" /> Staff can print a summary for another clinic or hospital.</p></div><button type="button" onClick={onOpenRecords} className="clinic-outline no-print mt-5 w-full">View and print care summary <ArrowRight size={17} /></button></section></div>
    </div>
    <p className="mt-6 text-xs leading-relaxed text-slate-500">Connected to the HDIMS clinical API. Vital entries are scored and persisted by the backend; this interface is not a substitute for clinical judgement.</p>
  </div>;
};
